spring:
  datasource:
    url: jdbc:mysql://192.168.177.130:3306/security?characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  redis:
    host: 192.168.177.130
#mybatis-plus:
#  mapper-locations: classpath:com/baizhi/mapper/*.xml
#  type-aliases-package: com.baizhi.entity
#logging:
#    level:
#      com.baizhi: debug

mybatis-plus:
  mapper-locations: classpath:com/baizhi/mapper/*.xml
  type-aliases-package: com.baizhi.entity